/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecAdminRouteImport } from './routes/rec-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewLinkIdRouteImport } from './routes/view.$linkId'
import { Route as LinkLinkIdRouteImport } from './routes/link.$linkId'

const RecAdminRoute = RecAdminRouteImport.update({
  id: '/rec-admin',
  path: '/rec-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewLinkIdRoute = ViewLinkIdRouteImport.update({
  id: '/view/$linkId',
  path: '/view/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkLinkIdRoute = LinkLinkIdRouteImport.update({
  id: '/link/$linkId',
  path: '/link/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/rec-admin': typeof RecAdminRoute
  '/link/$linkId': typeof LinkLinkIdRoute
  '/view/$linkId': typeof ViewLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/rec-admin': typeof RecAdminRoute
  '/link/$linkId': typeof LinkLinkIdRoute
  '/view/$linkId': typeof ViewLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/rec-admin': typeof RecAdminRoute
  '/link/$linkId': typeof LinkLinkIdRoute
  '/view/$linkId': typeof ViewLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/rec-admin' | '/link/$linkId' | '/view/$linkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/rec-admin' | '/link/$linkId' | '/view/$linkId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/rec-admin'
    | '/link/$linkId'
    | '/view/$linkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RecAdminRoute: typeof RecAdminRoute
  LinkLinkIdRoute: typeof LinkLinkIdRoute
  ViewLinkIdRoute: typeof ViewLinkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rec-admin': {
      id: '/rec-admin'
      path: '/rec-admin'
      fullPath: '/rec-admin'
      preLoaderRoute: typeof RecAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$linkId': {
      id: '/view/$linkId'
      path: '/view/$linkId'
      fullPath: '/view/$linkId'
      preLoaderRoute: typeof ViewLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/$linkId': {
      id: '/link/$linkId'
      path: '/link/$linkId'
      fullPath: '/link/$linkId'
      preLoaderRoute: typeof LinkLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RecAdminRoute: RecAdminRoute,
  LinkLinkIdRoute: LinkLinkIdRoute,
  ViewLinkIdRoute: ViewLinkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
